name: my_fome
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  
  uikit:
    path: ./uikit
  
  cupertino_icons: ^1.0.8
  mobx: ^2.4.0
  flutter_mobx: ^2.2.1+1
  dio: ^5.7.0
  validatorless: ^1.2.4
  get_it: ^7.7.0
  mask_text_input_formatter: ^2.9.0
  intl: ^0.20.2
  google_sign_in: ^6.2.2
  url_launcher: ^6.3.1
  flutter_getit: ^3.0.1
  image_picker: ^1.1.2
  jwt_decode: ^0.3.1
  flutter_launcher_icons: ^0.14.2
  flutter_native_splash: ^2.4.7
  lucid_validation: ^1.2.0
  result_dart: ^2.0.0
  envied: ^1.1.1
  share_plus: ^12.0.0
  go_router: ^15.1.1
  flutter_secure_storage: ^9.2.4
  path_provider: ^2.1.5
  pdf: ^3.11.3
  equatable: ^2.0.7
  flutter_pdfview: ^1.4.0+1
  cloudinary: ^1.2.0
  file_picker: ^10.1.9
  flutter_map: ^8.2.2
  latlong2: ^0.9.1

flutter_native_splash:
  color: "#fe0019"
  image: "assets/images/logos/logo-icon.png"
  android: true
  fullscreen: true

flutter_icons:
  image_path: "assets/images/logos/logo-icon.png"
  android: "launcher_icon"
  adaptive_icon_background: "#fe0019"
  adaptive_icon_foreground: "assets/images/logos/logo-icon.png"

  android_12:
    color: "#fe0019"  
    image: "assets/images/logos/logo-icon.png"  
    icon_background_color: "#fe0019" 


dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  mobx_codegen: ^2.6.2
  build_runner: ^2.4.13
  flutter_lints: ^6.0.0
  mocktail: ^1.0.4
  envied_generator: ^1.1.1


flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/logos/
    - assets/images/error/

  
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf

